### PR TITLE
Branch 42 pull request

### PR DESCRIPTION
**Pull request by voitsel**
with comment

### CODE REVIEW

**Comment by voitsel** [comment]
Api test issue comment pr

**Comment by voitsel** [comment]
Api test issue comment pr 2

**Comment by voitsel** [comment]
Api test issue comment pr 2

**Comment by voitsel** [comment]
Api test issue comment pr 2

Posted from Leverice

**Review by kara4k — CHANGES_REQUESTED** [review]
ф

**Pull request merged**
